### ISSUE TITLE
Name generator, index out of bounds (in samples)

### ISSUE THREAD

**Issue by Skaruts** [Vladar4/libtcod_nim#14]
When running the samples (112), when I select the name generator something goes out of bounds:
```
main.nim(1607)           main
main.nim(1169)           renderName
system.nim(2918)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```

(I'm not running the samples along with the repo, though, I just copied the code from `samples.nim` into a file, placed the fonts in `data/fonts` next to it, changed the `DATA_PATH` const in the code from `"../data/"` to `"./data/"` and compiled it. Not sure if any of that makes a difference.)

I've tried running it a few more times and it's happening every time I select the name generator, but just a few minutes ago I was able to select it for some reason, and it was throwing this into the console repeatedly:
```
Registered syllable sets are:
The name "" has not been found.
```
I never tried libtcod samples before, so I don't know what the normal behavior for the name generator is, but I found it odd that when I pressed `+` and `-` it showed something like `=====` (iirc, or maybe it was `"""""""`) on the screen. I supposed it should be showing generated names.

**Comment by Vladar4** [comment]
It looks like you didn't copied `data/namegen` dir.

**Comment by Skaruts** [comment]
Oh. Alright then. Thanks.

**Comment by Vladar4** [comment]
No problem!
