### ISSUE TITLE
Attempt to read from nil error when using consoleInitRoot

### ISSUE THREAD

**Issue by zetashift** [Vladar4/libtcod_nim#15]
The samples work fine so I'm not sure why this small snippet isn't working:

```nim
when isMainModule:
  consoleSetCustomFont(font, FONT_LAYOUT_ASCII_INROW)
  consoleInitRoot(ScreenWidth, ScreenHeight, "Demo", false, renderer)
  while not consoleIsWindowClosed():
    consoleSetDefaultForeground(nil, WHITE)
    consolePutChar(nil, 1, 1, '@', BKGND_NONE)
    consoleFlush()
    discard sysCheckForEvent((EVENT_KEY_PRESS.ord or EVENT_MOUSE.ord), addr(key), addr(mouse))
    if key.vk == K_ESCAPE: break
  libtcod.quit()
```
`renderer` is set to `RENDERER_SDL2` and I get the following error:
```
Traceback (most recent call last)
C:\Users\rishiPC\stack\dev\gamedev\ndtrl\src\main.nim(15) main
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
line 15 being the `consoleInitRoot` call.

**Comment by zetashift** [comment]
if I remove the renderer argument from `consoleInitRoot` I get:
```
libtcod 1.12.3 FATAL ERROR:
SDL : failed to create scaling surface
terminate called without an active exception
Traceback (most recent call last)
C:\Users\rishiPC\stack\dev\gamedev\ndtrl\src\main.nim(20) main
SIGABRT: Abnormal termination.
```

**Comment by zetashift** [comment]
It was not! It was related that `font` variable wasn't a correct path to the font. Weird error but I got it.
Thanks for the great library :D.

**Comment by Skaruts** [comment]
I get this error (and a crash) when switching to SDL or SDL2 renderers. The error always points to the `consoleFlush()` line. I'm reproducing this on the samples112, and I have no issues switching between other renderers, and everything seems to be working fine, so I'm quite clueless what the problem could be.

To be clear, I can use any SDL renderer if it's set as the starting renderer, but I can't switch to any of them.

**Comment by Vladar4** [comment]
Can't reproduce with libtcod 1.15.1. If you are using older version of the lib, try to update to the latest one.

**Comment by Skaruts** [comment]
Oh. I thought I needed 1.12.2, as it says in the readme. 

Seems like on 1.16.0-alpha-12 I have no more crashes.
Thanks.
