### ISSUE TITLE
Support libtcod 1.6

### ISSUE THREAD

**Issue by zetashift** [Vladar4/libtcod_nim#8]
How would one go about adding support for 1.6.x? 
https://libtcod.readthedocs.io/en/latest/upgrading.html
As far as I know 1.5.1 works well enough for most cases, so upgrading might not be even worth it.

**Comment by zetashift** [comment]
Yikes seems 1.7 got released too: https://bitbucket.org/libtcod/libtcod/downloads/

**Comment by Vladar4** [comment]
Thanks for the info. I'll look into it and see how much the API has changed, but probably after Nim v0.19 release.

**Comment by Vladar4** [comment]
> is it ready yet

Mostly, might have some bugs still. I'll merge it with the master branch when I finish debugging the samples demo.

> how do I start using it?

Just install the tcod170 branch (`nimble install libtcod_nim@#tcod170` IIRC). v1.7.0 is default, and to use v1.5.1 instead pass the `--define:tcod151` to the compiler.

> and can I close this now?

I plan to close it when tcod170 branch will be merged into master.

**Comment by zetashift** [comment]
Thanks! :D

**Comment by Vladar4** [comment]
Implemented in [v0.99](https://github.com/Vladar4/libtcod_nim/releases/tag/v0.99)
